plugins:
  - jest
  - promise
extends:
  - 'eslint:recommended'
  - 'plugin:promise/recommended'
env:
  browser: true
  es6: true
  node: true
  webextensions: true
  jest/globals: true
parserOptions:
  sourceType: module
  ecmaVersion: 2020
globals:
  process: true
rules:
  semi: 1
  no-undef: 2
  no-unused-vars:
    - error
    - varsIgnorePattern: "(Service|Filters)$"
